Repository microsoft/spring-cloud-azure, pull requests merged in 2018-07, with the labels that each got.

#35 Add telemetry dependency and configuration files.
  spring-cloud-azure-autoconfigure/pom.xml
  spring-cloud-azure-autoconfigure/src/main/resources/ApplicationInsights.xml
  spring-cloud-azure-autoconfigure/src/main/resources/META-INF/project.properties
Labels: BI, enhancement

#42 Add jacoco for code coverage.
  .travis.yml
  pom.xml
Labels: Code clean/quality/refactor, Documentation

#41 Add issue templates
  .github/ISSUE_TEMPLATE/custom.md
Labels: Documentation

#39 Add telemetry mode for spring cloud azure autoconfiguration, #38.
  pom.xml
  spring-cloud-azure-autoconfigure/pom.xml
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/cache/AzureRedisAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureProperties.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/eventhub/AzureEventHubAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/sql/AzureSqlAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/storage/AzureStorageAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryTracker.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryUtils.java
  spring-cloud-azure-autoconfigure/src/test/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfigurationTest.java
Labels: BI, New feature

#60 Inject ai instrumentation key as application.properties, #59.
  spring-cloud-azure-autoconfigure/pom.xml
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryProperties.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryTracker.java
  spring-cloud-azure-autoconfigure/src/main/resources/ApplicationInsights.xml
  spring-cloud-azure-autoconfigure/src/main/resources/META-INF/project.properties
  spring-cloud-azure-autoconfigure/src/main/resources/application.properties
  spring-cloud-azure-autoconfigure/src/test/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfigurationTest.java
Labels: Documentation, Refactor

#70 Add telemetry.config files.
  spring-cloud-azure-autoconfigure/pom.xml
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/context/AzureContextAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/resources/telemetry.config
  spring-cloud-azure-autoconfigure/src/test/resources/telemetry.config
Labels: BI, Documentation

#81 Use network hostname as event hub hostNamePrefix, #76.
  spring-integration-azure/src/main/java/com/microsoft/azure/spring/integration/eventhub/DefaultEventHubClientFactory.java
  spring-integration-azure/src/main/java/com/microsoft/azure/spring/integration/eventhub/HostnameHelper.java
Labels: enhancement

#86 fix sample commandline failed to locate credential file, #84.
  spring-cloud-azure-context/pom.xml
  spring-cloud-azure-context/src/main/java/com/microsoft/azure/spring/cloud/context/core/DefaultCredentialsProvider.java
  spring-cloud-azure-dependencies/pom.xml
Labels: bug, enhancement

#90 Refine sample code and documentation, #72.
  spring-cloud-azure-samples/spring-cloud-azure-cache-sample/README.adoc
  spring-cloud-azure-samples/spring-cloud-azure-cache-sample/src/main/resources/application.properties
  spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample/README.adoc
  spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample/src/main/java/com/example/SourceExample.java
  spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample/src/main/java/com/example/UserMessage.java
  spring-cloud-azure-samples/spring-cloud-azure-eventhub-binder-sample/src/main/resources/application.properties
  spring-cloud-azure-samples/spring-cloud-azure-servicebus-sample/src/main/java/example/ServiceBusQueueApplication.java
  spring-cloud-azure-samples/spring-cloud-azure-servicebus-sample/src/main/resources/application.properties
  spring-cloud-azure-samples/spring-cloud-azure-sql-sample/README.adoc
  spring-cloud-azure-samples/spring-cloud-azure-sql-sample/src/main/resources/application.properties
  spring-cloud-azure-samples/spring-cloud-azure-storage-sample/README.adoc
  spring-cloud-azure-samples/spring-cloud-azure-storage-sample/src/main/resources/application.properties
  spring-cloud-azure-samples/spring-cloud-stream-eventhub-kafka-sample/src/main/java/com/example/SinkExample.java
  spring-cloud-azure-samples/spring-cloud-stream-eventhub-kafka-sample/src/main/java/com/example/SourceExample.java
  spring-cloud-azure-samples/spring-cloud-stream-eventhub-kafka-sample/src/main/java/com/example/UserMessage.java
  spring-cloud-azure-samples/spring-cloud-stream-eventhub-kafka-sample/src/main/resources/application.properties
Labels: enhancement

#104 Add unused ApplicationInsight.xml to avoid confusing logs. , #103.
  spring-cloud-azure-autoconfigure/pom.xml
  spring-cloud-azure-autoconfigure/src/main/resources/ApplicationInsights.xml
Labels: enhancement

#113 Remove resourceGroup from telemetry data, fix #106.
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryAutoConfiguration.java
  spring-cloud-azure-autoconfigure/src/main/java/com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryTracker.java
Labels: enhancement

#121 Add azure data jpa sample, fix #119.
  spring-cloud-azure-samples/pom.xml
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/README.adoc
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/pom.xml
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/src/main/java/com/example/JpaApplication.java
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/src/main/java/com/example/User.java
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/src/main/java/com/example/UserRepository.java
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/src/main/java/com/example/WebController.java
  spring-cloud-azure-samples/spring-cloud-azure-data-jpa-sample/src/main/resources/application.properties
Labels: Sample

#155 Disable checkstyle plugin in sample build process. Fix #152
  spring-cloud-azure-samples/pom.xml
Labels: Cherry-pick
