Repository microsoft/spring-cloud-azure, pull requests merged in 2022-05, with the labels that each got.

#938 Update README.md.
  README.md
Labels: azure-spring

#942 Update README.md.
  README.md
Labels: feature-request, azure-spring, azure-spring-docs

#948 Fix pipeline broken link checker error
  .github/workflows/brokenLinkCheck.yml
  .github/workflows/scheduleCurrentLinkCheck.yaml
Labels: azure-spring

#922 Modify the generation format of the appendix page configuration properties table
  docs/pom.xml
  docs/src/main/asciidoc/_configprops_kv_secret.adoc
  docs/src/main/asciidoc/_configuration-properties-all.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-active-directory-b2c.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-active-directory.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-app-configuration.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-cosmos-db.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-event-hubs.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-key-vault-certificates.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-key-vault-secrets.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-service-bus-jms.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-service-bus.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-storage-blob.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-storage-file-share.adoc
  docs/src/main/asciidoc/_configuration-properties-azure-storage-queue.adoc
  docs/src/main/asciidoc/_configuration-properties-global.adoc
  docs/src/main/asciidoc/appendix.adoc
  pom.xml
  spring-cloud-azure-markdown-appdendix-generator/pom.xml
  spring-cloud-azure-markdown-appdendix-generator/src/main/java/com/azure/spring/cloud/internal/Main.java
  spring-cloud-azure-markdown-appdendix-generator/src/test/java/com/azure/spring/cloud/internal/GeneratorTests.java
  spring-cloud-azure-markdown-appdendix-generator/src/test/java/com/azure/spring/cloud/internal/MainTests.java
  spring-cloud-azure-markdown-appdendix-generator/src/test/resources/configuration-properties-output.md
  spring-cloud-azure-markdown-appdendix-generator/src/test/resources/with-azure-in-name.json
Labels: azure-spring

#940 Add GitHub action for creating sync reference documentation to MS Dcos PR
  .github/workflows/UpdatePropertiesTableInMSDocs.yaml
Labels: azure-spring, azure-spring-docs

#950 Update the filenames under the workflow directory and the way to build the azure-dev-docs-pr repository
  .github/workflows/broken-link-check.yml
  .github/workflows/markdown-link-check-config.json
  .github/workflows/schedule-current-link-check.yaml
  .github/workflows/update-docs.yaml
  .github/workflows/update-properties-table-in-ms-docs.yaml
  README.md
Labels: azure-spring

#951 Update sync properties table changes action name
  .github/workflows/update-properties-table-in-ms-docs.yaml
Labels: azure-spring

#954 Update gh-pages reference doc version from 4.1.0 to 4.2.0.
  docs/pom.xml
  pom.xml
  spring-cloud-azure-markdown-appdendix-generator/pom.xml
Labels: feature-request, azure-spring, client
